using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Game
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("\t \t \t \t WELCOME TO ROCK , PAPER & SCISSORS GAME !!!!\n\n\n");

            // make a string input for player and CPU
            string inputP , inputC;
            

            // now we make an integer input for computer to choose any random number to choose rock,ppr,scr

            int random;

            // THese ints are the initial score of both player and CPU

            int Playerscore=0;
            int CPUscore =0;

            Console.Write("Choose btw Rock , Paper and Scissors : ");
            
            //here player will give the entry or input
            inputP  = Console.ReadLine();
             
            //now we write a function for random no. that can be generated by PC

            Random rdm = new Random();
            // here we call int random which we write on 20th codeline
            random = rdm.Next(1,4);

            //Now for these random number which is btw 1-4 we have to make Switch cases for each no. and its case

            switch(random)
            {
                case 1:

                    inputC = "ROCK";

                    Console.WriteLine("Computer chooses Rock !");

                    if (inputP=="ROCK")
                    {
                        Console.WriteLine(" it's a DRAW");
                    }
                    else if (inputP== "PAPER")
                    {
                        Console.WriteLine(" YEahh Player Wins!!");
                        Playerscore++;
                    }
                    
                    else if (inputP=="SCISSORS")
                    {
                        Console.WriteLine("YOU Loose Buddy");
                        CPUscore++;
                    }
                         
                    
                    break;


                case 2:
                    inputC = "PAPER";
                    
                    Console.WriteLine("Computer chooses Paper !");
                    if (inputP == "PAPER")
                    {
                        Console.WriteLine(" it's a DRAW");
                    }
                    else if (inputP == "SCISSORS")
                    {
                        Console.WriteLine(" YEahh Player Wins!!");
                        Playerscore++;
                    }

                    else if (inputP == "ROCK")
                    {
                        Console.WriteLine("YOU Loose Buddy");
                        CPUscore++;
                    }
                    break;


                case 3:
                    inputC = "SCISSORS";
                    
                    Console.WriteLine("Computer chooses Scissors !");
                    if (inputP == "SCISSORS")
                    {
                        Console.WriteLine(" it's a DRAW");
                    }
                    else if (inputP == "ROCK")
                    {
                        Console.WriteLine(" YEahh Player Wins!!");
                        Playerscore++;
                    }

                    else if (inputP == "PAPER")
                    {
                        Console.WriteLine("YOU Loose Buddy");
                        CPUscore++;
                    }
                    break;

                


            }
            

            Console.ReadLine();



        }
    }
}
